modbus:
  port: COM10
  rate: 9600
mqtt:
  url: tcp://host
devices:
  - deviceId: 1
    topic: /DEYE
    data:
      - topic: ''
        startRegister: 604
        numberRegisters: 22
        type: 3
        registers:
          - { channelId: 2814877, channelField: 4, factor: 1, name: A phase power on the inner side of the grid, offset: 0, topic: /grid/in/phase/A/power, type: S16} #!!
          - { channelId: 2814877, channelField: 5, factor: 1, name: B phase power on the inner side of the grid, offset: 1, topic: /grid/in/phase/B/power, type: S16} #!!
          - { channelId: 2814877, channelField: 6, factor: 1, name: C phase power on the inner side of the grid, offset: 2, topic: /grid/in/phase/C/power, type: S16} #!!
          - { channelId: 2814877, channelField: 1, factor: 1, name: Out-of-grid - power A, offset: 12, topic: /grid/out/phase/A/power, type: S16} #!!
          - { channelId: 2814877, channelField: 2, factor: 1, name: Out-of-grid - power B, offset: 13, topic: /grid/out/phase/B/power, type: S16} #!!
          - { channelId: 2814877, channelField: 3, factor: 1, name: Out-of-grid - power C, offset: 14, topic: /grid/out/phase/C/power, type: S16} #!!
      - topic: ''
        startRegister: 640
        numberRegisters: 16
        type: 3
        registers:
          - { channelId: 2814878, channelField: 1, factor: 1, name: Load phase power A, offset: 10, topic: /inverter/load/phase/A/power, type: S16 } #!!
          - { channelId: 2814878, channelField: 2, factor: 1, name: Load phase power B, offset: 11, topic: /inverter/load/phase/B/power, type: S16 } #!!
          - { channelId: 2814878, channelField: 3, factor: 1, name: Load phase power C, offset: 12, topic: /inverter/load/phase/C/power, type: S16 } #!!
      - topic: ''
        startRegister: 586
        numberRegisters: 6
        type: 3
        registers:
          - { channelId: 2814869, channelField: 2, factor: 0.01, name: Battery Temperature, offset: 0, topic: /battery/temperature, type: U16} #586 #!!
          - { channelId: 2814869, channelField: 1, factor: 1, name: Battery SOC, offset: 2, topic: /battery/soc, type: U16} #588 #!!
          - { channelId: 2814869, channelField: 3, factor: 1, name: Battery Power, offset: 4, topic: /battery/power, type: U16} #590 #!!
      - topic: ''
        startRegister: 514
        numberRegisters: 22
        type: 3
        registers:
          - { channelId: 2814869, channelField: 4, factor: 0.1, name: Today charge of the battery, offset: 0, topic: /inverter/stat/battery/charge/today, type: U16} #514 #!!
          - { channelId: 2814869, channelField: 5, factor: 0.1, name: Today discharge	of the battery, offset: 1, topic: /inverter/stat/battery/discharge/today, type: U16} #515 #!!      
          - { channelId: 2814877, channelField: 7, factor: 0.1, name: Day_GridBuy_Power Wh, offset: 6, topic: /inverter/stat/grid/power/buy/today, type: U16} #520 #!!
          - { channelId: 2814877, channelField: 8, factor: 0.1, name: Day_GridSell_Power Wh, offset: 7, topic: /inverter/stat/grid/power/sell/today, type: U16} #521 #!!
          - { channelId: 2814878, channelField: 4, factor: 0.1, name: Day_Load_Power Wh, offset: 12, topic: /inverter/stat/power/load/day, type: U16} #526 #!!

